parser: "babel-eslint"

extends: "eslint:recommended"

plugins:
  - "babel"
  - "react"

env:
  browser: true
  es6:     true
  node:    true

parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
  sourceType: "module"

rules:
  array-bracket-spacing: [2, "never"]
  arrow-spacing: [2, {before: true, after: true}]
  brace-style: [2, "1tbs"]
  camelcase: [1, {properties: "never"}]
  comma-style: [2, "last"]
  complexity: [1, 12]
  computed-property-spacing: [2, "never"]
  consistent-return: 0
  eol-last: [2, "always"]
  func-names: 1
  guard-for-in: 2
  indent: [2, 4, {SwitchCase: 1}]
  jsx-quotes: [2, "prefer-double"]
  keyword-spacing: [2, {"after": true, "before": true}]
  linebreak-style: [2, "unix"]
  max-len: [2, 120, 4]
  new-cap: [2, {newIsCap: true, capIsNew: false}]
  no-bitwise: 2
  no-class-assign: 2
  no-console: 0
  no-const-assign: 2
  no-else-return: 2
  no-eq-null: 2
  no-extra-parens: 0
  no-floating-decimal: 2
  no-inner-declarations: [2, "both"]
  no-lonely-if: 2
  no-multiple-empty-lines: [2, {max: 3}]
  no-self-compare: 2
  no-underscore-dangle: 0
  no-unused-expressions: 0
  no-use-before-define: 0
  no-useless-call: 2
  no-void: 2
  object-curly-spacing: [2, "never"]
  prefer-spread: 1
  quotes: [2, "single"]
  react/display-name: 2
  react/jsx-boolean-value: [2, "never"]
  react/jsx-indent: [2, 4]
  react/jsx-no-undef: 2
  react/jsx-pascal-case: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/react-in-jsx-scope: 2
  react/self-closing-comp: 2
  react/wrap-multilines: 2
  semi: [2, "always"]
  space-before-blocks: [2, "always"]
  space-before-function-paren: [2, "always"]
  space-in-parens: [2, "never"]
  strict: [0, "global"]
  valid-jsdoc: 1
  wrap-iife: [2, "any"]
  yoda: [1, "never"]
