extends:
  - ./default.json
  - prettier
  - prettier/react

plugins:
  - prettier

rules:
  prettier/prettier:
    - error
    - bracketSpacing: false
      printWidth: 80
      singleQuote: true
      tabWidth: 2
