parser: '@typescript-eslint/parser'

extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
  - './default'

plugins:
  - '@typescript-eslint'

parserOptions:
  project: './tsconfig.json'
  warnOnUnsupportedTypeScriptVersion: false

rules: {}
