parser: '@typescript-eslint/parser'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
  - 'prettier/react'

plugins:
  - '@typescript-eslint'
  - 'react'
  - 'prettier'

env:
  browser: true
  es6: true
  node: true

parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  warnOnUnsupportedTypeScriptVersion: false

settings:
  react:
    version: detect

rules:
  prettier/prettier:
    - error
    - arrowParens: avoid
      bracketSpacing: true
      printWidth: 80
      singleQuote: true
      tabWidth: 2
      trailingComma: all
