parser: '@typescript-eslint/parser'

extends:
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
  - './default'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'

plugins:
  - '@typescript-eslint'

parserOptions:
  project: './tsconfig.json'
  warnOnUnsupportedTypeScriptVersion: false

rules:
  no-extra-parens: 0
  no-use-before-define: 0
