parser: '@typescript-eslint/parser'

extends:
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
  - './default'
  - 'plugin:@typescript-eslint/recommended'

plugins:
  - '@typescript-eslint'

parserOptions:
  project: './tsconfig.json'
  warnOnUnsupportedTypeScriptVersion: false

rules:
  '@typescript-eslint/no-extra-semi': 0
  '@typescript-eslint/no-unused-vars': 2
  no-extra-parens: 0
  no-use-before-define: 0
